package com.project.zariya.core.navigation

import android.app.Activity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.navigation.NavHostController
import androidx.navigation.NavType
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.navArgument
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.project.zariya.feature.analytics.presentation.AnalyticsScreen
import com.project.zariya.feature.auth.presentation.AuthViewModel
import com.project.zariya.feature.auth.presentation.AuthScreen
import com.project.zariya.feature.home.presentation.HomeScreen
import com.project.zariya.feature.medicine.presentation.add_edit.AddEditMedicineScreen
import com.project.zariya.feature.medicine.presentation.detail.MedicineDetailScreen
import com.project.zariya.feature.medicine.presentation.list.MedicineListScreen
import com.project.zariya.feature.reminder.presentation.add_edit.AddEditReminderScreen
import com.project.zariya.feature.reminder.presentation.list.ReminderListScreen
import com.project.zariya.feature.scanner.presentation.ScannerScreen
import com.project.zariya.feature.scanner.presentation.ScanResultScreen
import com.project.zariya.feature.interaction.presentation.InteractionScreen
import com.project.zariya.feature.health.presentation.HealthDashboardScreen

@Composable
fun ZariyaNavHost(
    navController: NavHostController,
    modifier: Modifier = Modifier,
    startDestination: String = Route.Home.route,
    authViewModel: AuthViewModel? = null
) {
    val context = LocalContext.current

    // Google Sign-In launcher
    val googleSignInLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.StartActivityForResult()
    ) { result ->
        if (result.resultCode == Activity.RESULT_OK) {
            val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
            try {
                val account = task.getResult(ApiException::class.java)
                account?.idToken?.let { idToken ->
                    authViewModel?.signInWithGoogle(idToken)
                }
            } catch (_: ApiException) {
                // Google sign-in failed
            }
        }
    }

    val launchGoogleSignIn: () -> Unit = {
        try {
            // default_web_client_id is auto-generated by google-services plugin
            // It only exists after enabling Google Sign-In in Firebase Console
            val webClientId = context.getString(
                context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
            )
            if (webClientId.isNotEmpty()) {
                val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                    .requestIdToken(webClientId)
                    .requestEmail()
                    .build()
                val googleSignInClient = GoogleSignIn.getClient(context, gso)
                googleSignInLauncher.launch(googleSignInClient.signInIntent)
            }
        } catch (_: Exception) {
            // Web client ID not available yet — user needs to enable Google Sign-In in Firebase Console
        }
    }

    NavHost(
        navController = navController,
        startDestination = startDestination,
        modifier = modifier
    ) {
        // ========== AUTH SCREENS ==========

        composable(Route.Auth.route) {
            authViewModel?.let { vm ->
                AuthScreen(
                    onAuthSuccess = {
                        navController.navigate(Route.Home.route) {
                            popUpTo(0) { inclusive = true }
                        }
                    },
                    onGoogleSignIn = launchGoogleSignIn,
                    viewModel = vm
                )
            }
        }

        // ========== APP SCREENS ==========

        // Home
        composable(Route.Home.route) {
            HomeScreen(
                onNavigateToMedicines = { navController.navigate(Route.MedicineList.route) },
                onNavigateToReminders = { navController.navigate(Route.ReminderList.route) },
                onNavigateToProfile = { navController.navigate(Route.ProfileList.route) },
                onNavigateToScanner = { navController.navigate(Route.Scanner.route) },
                onNavigateToInteractions = { navController.navigate(Route.DrugInteractions.route) },
                onNavigateToHealth = { navController.navigate(Route.HealthDashboard.route) },
                onNavigateToAnalytics = { navController.navigate(Route.Analytics.route) },
                onNavigateToForHer = { navController.navigate(Route.ForHer.route) },
                onNavigateToInventory = { navController.navigate(Route.InventoryHealth.route) }
            )
        }

        // Inventory Health
        composable(Route.InventoryHealth.route) {
            com.project.zariya.feature.medicine.presentation.inventory.InventoryHealthDashboard(
                onNavigateBack = { navController.popBackStack() },
                onMedicineClick = { id -> navController.navigate(Route.MedicineDetail.createRoute(id)) }
            )
        }

        // For Her
        composable(Route.ForHer.route) {
            com.project.zariya.feature.for_her.presentation.home.ForHerHomeScreen(
                onNavigateBack = { navController.popBackStack() },
                onNavigateToLuna = { navController.navigate(Route.ForHerLuna.route) }
            )
        }

        // For Her Luna Coach
        composable(Route.ForHerLuna.route) {
            com.project.zariya.feature.for_her.presentation.luna.LunaCoachScreen(
                onNavigateBack = { navController.popBackStack() }
            )
        }

        // Medicine List
        composable(Route.MedicineList.route) {
            MedicineListScreen(
                onNavigateToAddMedicine = {
                    navController.navigate(Route.AddEditMedicine.createRoute(null))
                },
                onNavigateToMedicineDetail = { id ->
                    navController.navigate(Route.MedicineDetail.createRoute(id))
                }
            )
        }

        // Add/Edit Medicine
        composable(
            route = Route.AddEditMedicine.route,
            arguments = listOf(navArgument("id") { type = NavType.StringType; defaultValue = "" })
        ) {
            AddEditMedicineScreen(
                onNavigateBack = { navController.popBackStack() },
                onNavigateToAddReminder = { medicineId ->
                    navController.navigate(Route.AddEditReminder.createRoute(id = null, medicineId = medicineId)) {
                        popUpTo(Route.AddEditMedicine.route) { inclusive = true }
                    }
                }
            )
        }

        // Medicine Detail
        composable(
            route = Route.MedicineDetail.route,
            arguments = listOf(navArgument("id") { type = NavType.StringType })
        ) { backStackEntry ->
            val medicineId = backStackEntry.arguments?.getString("id") ?: ""
            MedicineDetailScreen(
                medicineId = medicineId,
                onNavigateBack = { navController.popBackStack() },
                onNavigateToEdit = { id ->
                    navController.navigate(Route.AddEditMedicine.createRoute(id))
                },
                onNavigateToAddReminder = {
                    navController.navigate(Route.AddEditReminder.createRoute(id = null, medicineId = medicineId))
                }
            )
        }

        // Reminder List
        composable(Route.ReminderList.route) {
            ReminderListScreen(
                onNavigateToAddReminder = {
                    navController.navigate(Route.AddEditReminder.createRoute(null))
                },
                onNavigateToEditReminder = { id ->
                    navController.navigate(Route.AddEditReminder.createRoute(id))
                },
                onNavigateBack = { navController.popBackStack() }
            )
        }

        composable(
            route = Route.AddEditReminder.route,
            arguments = listOf(
                navArgument("id") { type = NavType.StringType; defaultValue = "" },
                navArgument("medicineId") { type = NavType.StringType; defaultValue = "" }
            )
        ) {
            AddEditReminderScreen(
                onNavigateBack = { navController.popBackStack() }
            )
        }

        // Scanner (CameraX + ML Kit OCR)
        composable(Route.Scanner.route) {
            ScannerScreen(
                onNavigateBack = { navController.popBackStack() },
                onNavigateToResults = {
                    navController.navigate(Route.ScanResult.route) {
                        launchSingleTop = true
                    }
                }
            )
        }

        // Scan Results
        composable(Route.ScanResult.route) {
            ScanResultScreen(
                onNavigateBack = {
                    navController.popBackStack(Route.Scanner.route, inclusive = false)
                },
                onAddSelectedMedicines = { medicines ->
                    navController.popBackStack(Route.Home.route, inclusive = false)
                    navController.navigate(Route.MedicineList.route)
                }
            )
        }

        // Drug Interactions
        composable(Route.DrugInteractions.route) {
            InteractionScreen(
                onNavigateBack = { navController.popBackStack() }
            )
        }

        // Health Dashboard
        composable(Route.HealthDashboard.route) {
            HealthDashboardScreen(
                onNavigateBack = { navController.popBackStack() }
            )
        }

        // Analytics
        composable(Route.Analytics.route) {
            AnalyticsScreen(
                onNavigateBack = { navController.popBackStack() }
            )
        }

        // Profile
        composable(Route.ProfileList.route) {
            com.project.zariya.feature.profile.presentation.ProfileListScreen(
                onNavigateToAddProfile = {
                    navController.navigate(Route.AddEditProfile.createRoute(null))
                },
                onNavigateToEditProfile = { id ->
                    navController.navigate(Route.AddEditProfile.createRoute(id))
                },
                onNavigateBack = { navController.popBackStack() },
                onLogout = {
                    authViewModel?.signOut()
                    
                    try {
                        val webClientId = context.getString(
                            context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
                        )
                        if (webClientId.isNotEmpty()) {
                            val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                                .requestIdToken(webClientId)
                                .requestEmail()
                                .build()
                            val googleSignInClient = GoogleSignIn.getClient(context, gso)
                            googleSignInClient.signOut().addOnCompleteListener {
                                navController.navigate(Route.Auth.route) {
                                    popUpTo(0) { inclusive = true }
                                }
                            }
                            return@ProfileListScreen
                        }
                    } catch (_: Exception) {}

                    navController.navigate(Route.Auth.route) {
                        popUpTo(0) { inclusive = true }
                    }
                }
            )
        }

        // Add/Edit Profile
        composable(
            route = Route.AddEditProfile.route,
            arguments = listOf(navArgument("id") { type = NavType.StringType; defaultValue = "" })
        ) {
            com.project.zariya.feature.profile.presentation.add_edit.AddEditProfileScreen(
                onNavigateBack = { navController.popBackStack() }
            )
        }
    }
}

@Composable
fun PlaceholderScreen(title: String) {
    Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
        Text(text = title)
    }
}
